"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-09-08 18:59:11.252587
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtags",
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hashtags")),
    )
    op.create_index(op.f("ix_hashtags_tag"), "hashtags", ["tag"], unique=True)
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("bio", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=64), nullable=True),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("banner_url", sa.String(length=512), nullable=True),
        sa.Column("telegram_username", sa.String(length=64), nullable=True),
        sa.Column("language_code", sa.String(length=8), nullable=True),
        sa.Column(
            "is_telegram_premium",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "followers_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "following_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "pulses_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "blocks",
        sa.Column("blocker_id", sa.BigInteger(), nullable=False),
        sa.Column("blocked_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "blocker_id <> blocked_id", name=op.f("ck_blocks_no_self_block")
        ),
        sa.ForeignKeyConstraint(
            ["blocked_id"],
            ["users.id"],
            name=op.f("fk_blocks_blocked_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"],
            ["users.id"],
            name=op.f("fk_blocks_blocker_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id", name=op.f("pk_blocks")),
    )
    op.create_index("ix_blocks_blocked", "blocks", ["blocked_id"], unique=False)
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.BigInteger(), nullable=False),
        sa.Column("followee_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "follower_id <> followee_id", name=op.f("ck_follows_no_self_follow")
        ),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["users.id"],
            name=op.f("fk_follows_followee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name=op.f("pk_follows")),
    )
    op.create_index(
        "ix_follows_followee_created",
        "follows",
        ["followee_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "pulses",
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.String(length=280), server_default="", nullable=False),
        sa.Column("reply_to_id", sa.BigInteger(), nullable=True),
        sa.Column("repulse_of_id", sa.BigInteger(), nullable=True),
        sa.Column("quote_of_id", sa.BigInteger(), nullable=True),
        sa.Column("conversation_id", sa.BigInteger(), nullable=True),
        sa.Column("like_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reply_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "repulse_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("quote_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "bookmark_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("view_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "repulse_of_id IS NULL OR content = ''",
            name=op.f("ck_pulses_repost_has_no_content"),
        ),
        sa.CheckConstraint(
            "(reply_to_id IS NOT NULL)::int + (repulse_of_id IS NOT NULL)::int + (quote_of_id IS NOT NULL)::int <= 1",
            name=op.f("ck_pulses_single_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_pulses_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quote_of_id"],
            ["pulses.id"],
            name=op.f("fk_pulses_quote_of_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["pulses.id"],
            name=op.f("fk_pulses_reply_to_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repulse_of_id"],
            ["pulses.id"],
            name=op.f("fk_pulses_repulse_of_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pulses")),
    )
    op.create_index(
        "ix_pulses_author_created",
        "pulses",
        ["author_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_pulses_conversation_id"), "pulses", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_pulses_created_at"), "pulses", ["created_at"], unique=False)
    op.create_index(
        "ix_pulses_live_created",
        "pulses",
        [sa.text("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_pulses_reply_to_created",
        "pulses",
        ["reply_to_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_pulses_author_repulse",
        "pulses",
        ["author_id", "repulse_of_id"],
        unique=True,
        postgresql_where=sa.text("repulse_of_id IS NOT NULL"),
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("pulse_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_bookmarks_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_bookmarks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "pulse_id", name=op.f("pk_bookmarks")),
    )
    op.create_index(
        "ix_bookmarks_user_created", "bookmarks", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "likes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("pulse_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_likes_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "pulse_id", name=op.f("pk_likes")),
    )
    op.create_index("ix_likes_pulse", "likes", ["pulse_id"], unique=False)
    op.create_index(
        "ix_likes_user_created", "likes", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "media",
        sa.Column("uploader_id", sa.BigInteger(), nullable=False),
        sa.Column("pulse_id", sa.BigInteger(), nullable=True),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=420), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_media_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
            name=op.f("fk_media_uploader_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_storage_key")),
    )
    op.create_index(op.f("ix_media_created_at"), "media", ["created_at"], unique=False)
    op.create_index(op.f("ix_media_pulse_id"), "media", ["pulse_id"], unique=False)
    op.create_index(op.f("ix_media_uploader_id"), "media", ["uploader_id"], unique=False)
    op.create_table(
        "mentions",
        sa.Column("pulse_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_mentions_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mentions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pulse_id", "user_id", name=op.f("pk_mentions")),
    )
    op.create_index("ix_mentions_user", "mentions", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("recipient_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "LIKE",
                "REPLY",
                "REPULSE",
                "QUOTE",
                "FOLLOW",
                "MENTION",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("pulse_id", sa.BigInteger(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_notifications_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_notifications_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_recipient_created",
        "notifications",
        ["recipient_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["recipient_id"],
        unique=False,
        postgresql_where=sa.text("is_read = false"),
    )
    op.create_table(
        "pulse_hashtags",
        sa.Column("pulse_id", sa.BigInteger(), nullable=False),
        sa.Column("hashtag_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hashtag_id"],
            ["hashtags.id"],
            name=op.f("fk_pulse_hashtags_hashtag_id_hashtags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pulse_id"],
            ["pulses.id"],
            name=op.f("fk_pulse_hashtags_pulse_id_pulses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pulse_id", "hashtag_id", name=op.f("pk_pulse_hashtags")),
    )
    op.create_index(
        op.f("ix_pulse_hashtags_created_at"), "pulse_hashtags", ["created_at"], unique=False
    )
    op.create_index(
        "ix_pulse_hashtags_tag_created",
        "pulse_hashtags",
        ["hashtag_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pulse_hashtags_tag_created", table_name="pulse_hashtags")
    op.drop_index(op.f("ix_pulse_hashtags_created_at"), table_name="pulse_hashtags")
    op.drop_table("pulse_hashtags")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("is_read = false"),
    )
    op.drop_index("ix_notifications_recipient_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_mentions_user", table_name="mentions")
    op.drop_table("mentions")
    op.drop_index(op.f("ix_media_uploader_id"), table_name="media")
    op.drop_index(op.f("ix_media_pulse_id"), table_name="media")
    op.drop_index(op.f("ix_media_created_at"), table_name="media")
    op.drop_table("media")
    op.drop_index("ix_likes_user_created", table_name="likes")
    op.drop_index("ix_likes_pulse", table_name="likes")
    op.drop_table("likes")
    op.drop_index("ix_bookmarks_user_created", table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_index(
        "uq_pulses_author_repulse",
        table_name="pulses",
        postgresql_where=sa.text("repulse_of_id IS NOT NULL"),
    )
    op.drop_index("ix_pulses_reply_to_created", table_name="pulses")
    op.drop_index(
        "ix_pulses_live_created",
        table_name="pulses",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_pulses_created_at"), table_name="pulses")
    op.drop_index(op.f("ix_pulses_conversation_id"), table_name="pulses")
    op.drop_index("ix_pulses_author_created", table_name="pulses")
    op.drop_table("pulses")
    op.drop_index("ix_follows_followee_created", table_name="follows")
    op.drop_table("follows")
    op.drop_index("ix_blocks_blocked", table_name="blocks")
    op.drop_table("blocks")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_hashtags_tag"), table_name="hashtags")
    op.drop_table("hashtags")
    # ### end Alembic commands ###
