"""channel history import

Revision ID: 005
Revises: 004
Create Date: 2026-09-12 19:46:36.017891
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "005"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels",
        sa.Column(
            "import_status",
            sa.String(length=16),
            server_default=sa.text("'idle'"),
            nullable=False,
        ),
    )
    op.add_column(
        "channels",
        sa.Column(
            "import_total", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "channels",
        sa.Column("import_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "channels", sa.Column("import_error", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "channels", sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("pulses", sa.Column("source_channel_id", sa.BigInteger(), nullable=True))
    op.add_column("pulses", sa.Column("source_message_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "pulses", sa.Column("source_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "pulses",
        sa.Column("reactions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        "ix_pulses_source_date",
        "pulses",
        ["author_id", sa.text("source_date DESC")],
        unique=False,
        postgresql_where=sa.text("source_channel_id IS NOT NULL"),
    )
    op.create_index(
        "uq_pulses_source_message",
        "pulses",
        ["source_channel_id", "source_message_id"],
        unique=True,
        postgresql_where=sa.text("source_channel_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pulses_source_message",
        table_name="pulses",
        postgresql_where=sa.text("source_channel_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_pulses_source_date",
        table_name="pulses",
        postgresql_where=sa.text("source_channel_id IS NOT NULL"),
    )
    op.drop_column("pulses", "reactions")
    op.drop_column("pulses", "source_date")
    op.drop_column("pulses", "source_message_id")
    op.drop_column("pulses", "source_channel_id")
    op.drop_column("channels", "imported_at")
    op.drop_column("channels", "import_error")
    op.drop_column("channels", "import_done")
    op.drop_column("channels", "import_total")
    op.drop_column("channels", "import_status")
    # ### end Alembic commands ###
