"""automated accounts

Revision ID: 007
Revises: 006
Create Date: 2026-09-12 21:04:15.618489
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "007"
down_revision: str | None = "006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("character", sa.Text(), nullable=False),
        sa.Column(
            "language", sa.String(length=8), server_default=sa.text("'en'"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "post_every_minutes",
            sa.Integer(),
            server_default=sa.text("180"),
            nullable=False,
        ),
        sa.Column(
            "reply_chance", sa.Float(), server_default=sa.text("0.25"), nullable=False
        ),
        sa.Column("like_chance", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column(
            "repulse_chance", sa.Float(), server_default=sa.text("0.08"), nullable=False
        ),
        sa.Column("last_posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_acted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posts_made", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "replies_made", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "tokens_used", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "post_every_minutes >= 5", name=op.f("ck_personas_cadence_is_sane")
        ),
        sa.CheckConstraint(
            "reply_chance BETWEEN 0 AND 1 AND like_chance BETWEEN 0 AND 1 AND repulse_chance BETWEEN 0 AND 1",
            name=op.f("ck_personas_chances_are_probabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_personas_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
        sa.UniqueConstraint("user_id", name=op.f("uq_personas_user_id")),
    )
    op.create_index(
        op.f("ix_personas_created_at"), "personas", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_personas_is_active"), "personas", ["is_active"], unique=False)
    op.add_column(
        "users",
        sa.Column(
            "is_automated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(op.f("ix_users_is_automated"), "users", ["is_automated"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_automated"), table_name="users")
    op.drop_column("users", "is_automated")
    op.drop_index(op.f("ix_personas_is_active"), table_name="personas")
    op.drop_index(op.f("ix_personas_created_at"), table_name="personas")
    op.drop_table("personas")
    # ### end Alembic commands ###
