"""follow accepted notification

Revision ID: 008
Revises: 007
Create Date: 2026-09-12 21:31:25.533253
"""

from collections.abc import Sequence

from alembic import op

revision: str = "008"
down_revision: str | None = "007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not detect new values on a native enum. Approving a
    # follow request now tells the requester they were accepted, which is a
    # different thing from being followed and so needs its own kind.
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'FOLLOW_ACCEPTED'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres cannot drop a value from an enum, and rows may reference it.
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
